development:
  adapter: postgresql
  encoding: unicode
  database: alonablue_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: alonablue_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: alonablue_production
  pool: 5
  username: postgres
  password: